/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.InventoryManager;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.State.State;
import Business.UserAccount.UserAccount;
import Business.Vendor.Vendor;
import UserInterface.MainJFrame;
import java.awt.CardLayout;
import java.awt.Image;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author rajsarode
 */
public class InventoryManagerHomeJpanel extends javax.swing.JPanel {
    
    EcoSystem system;
    Enterprise enterprise;
    UserAccount account;
    
    ArrayList<Enterprise> countyEnterpriseArray = new ArrayList<Enterprise>();
    private Vendor vendor;
    /**
     * Creates new form InventoryManagerHomeJpanel
     */
    public InventoryManagerHomeJpanel(EcoSystem system, Enterprise enterprise, UserAccount account) {
        this.system = system;
        this.enterprise = enterprise;
        this.account = account;
        initComponents();
        setModel();
//        setLogo();
//        setBackground();
    }
    
    private void setModel() {
        int fl2=0;
        
        for(Vendor ven:enterprise.getVendorDirectory().getVendorsArray()){
            
            for(UserAccount ua:ven.getUserAccountDirectory().getUserAccountList()){
                if(ua.getUsername().equals(account.getUsername())){
                    this.vendor = ven;
                    fl2=1;
                    break;
                }
            }
            if(fl2==1){
                break;
            }
        }
        
        ArrayList<Enterprise> countyEnterprises = new ArrayList();
        State net = null;
        int fl=0;
        for(State state: system.getStateList()){
            for(Enterprise ent: state.getEnterpriseDirectory().getEnterpriseListArray()){
                if(ent.getName() == enterprise.getName()){
                    fl=1;
                    net = state;
                    break;
                }
                if(fl==1){
                    break;
                }
            }
        }
        for(Enterprise ent:net.getEnterpriseDirectory().getEnterpriseListArray()){
            if(ent.getEnterpriseType().getValue().equals("County")){
                countyEnterpriseArray.add(ent);
            }
        }
    }
    
//    private void setLogo() {
//        Image image = null;
//        try {
//            image = ImageIO.read(getClass().getResource("/UI/logo.png"));
//        } catch (IOException ex) {
//            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
//        }
//
//        Image scaledImg = image.getScaledInstance(120, 200, Image.SCALE_SMOOTH);
//        ImageIcon icon = new ImageIcon(scaledImg);
//        imgLogo.setIcon(icon);
//    }
//    
//    private void setBackground() {
//        
//        Image image = null;
//        try {
//                image = ImageIO.read(getClass().getResource("/UI/DistributionEnterpriseAdmin/distributionbg.jpeg"));
//        } catch (IOException ex) {
//            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
//        }
//
//        Image scaledImg = image.getScaledInstance(1180, 930, Image.SCALE_SMOOTH);
//        ImageIcon icon = new ImageIcon(scaledImg);
//        System.out.println(icon);
//        bgImage.setIcon(icon);
//    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        OptionsJPanel = new javax.swing.JPanel();
        btnViewOrderHistory = new javax.swing.JButton();
        btnPlaceShippingOrder = new javax.swing.JButton();
        btnAssignDeliveryPartner = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        ActivityJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jSplitPane1.setDividerLocation(250);

        OptionsJPanel.setBackground(new java.awt.Color(0, 0, 0));
        OptionsJPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnViewOrderHistory.setBackground(new java.awt.Color(255, 153, 153));
        btnViewOrderHistory.setFont(new java.awt.Font("Myanmar MN", 0, 13)); // NOI18N
        btnViewOrderHistory.setText("View Order History");
        btnViewOrderHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewOrderHistoryActionPerformed(evt);
            }
        });

        btnPlaceShippingOrder.setBackground(new java.awt.Color(255, 153, 153));
        btnPlaceShippingOrder.setFont(new java.awt.Font("Myanmar MN", 0, 13)); // NOI18N
        btnPlaceShippingOrder.setText("Place Shipping Order");
        btnPlaceShippingOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceShippingOrderActionPerformed(evt);
            }
        });

        btnAssignDeliveryPartner.setBackground(new java.awt.Color(255, 153, 153));
        btnAssignDeliveryPartner.setFont(new java.awt.Font("Myanmar MN", 0, 13)); // NOI18N
        btnAssignDeliveryPartner.setText("Assign Delivery Partner");
        btnAssignDeliveryPartner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignDeliveryPartnerActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(255, 153, 153));
        btnLogout.setFont(new java.awt.Font("Myanmar MN", 0, 13)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OptionsJPanelLayout = new javax.swing.GroupLayout(OptionsJPanel);
        OptionsJPanel.setLayout(OptionsJPanelLayout);
        OptionsJPanelLayout.setHorizontalGroup(
            OptionsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OptionsJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OptionsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAssignDeliveryPartner, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlaceShippingOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewOrderHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(OptionsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(OptionsJPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        OptionsJPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAssignDeliveryPartner, btnPlaceShippingOrder, btnViewOrderHistory});

        OptionsJPanelLayout.setVerticalGroup(
            OptionsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OptionsJPanelLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(btnViewOrderHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPlaceShippingOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAssignDeliveryPartner, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(945, Short.MAX_VALUE))
            .addGroup(OptionsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(OptionsJPanelLayout.createSequentialGroup()
                    .addContainerGap(1033, Short.MAX_VALUE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(127, 127, 127)))
        );

        OptionsJPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAssignDeliveryPartner, btnPlaceShippingOrder, btnViewOrderHistory});

        jSplitPane1.setLeftComponent(OptionsJPanel);

        ActivityJPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ActivityJPanel.setLayout(new java.awt.CardLayout());
        ActivityJPanel.add(jLabel1, "card2");

        jSplitPane1.setRightComponent(ActivityJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewOrderHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewOrderHistoryActionPerformed
        // TODO add your handling code here:

        InventoryViewOrderHistoryJPanel managerOrderJPanel = new InventoryViewOrderHistoryJPanel(account, countyEnterpriseArray, vendor);
        ActivityJPanel.add("InventoryViewOrderHistoryJPanel", managerOrderJPanel);
        CardLayout layout = (CardLayout)ActivityJPanel.getLayout();
        layout.next(ActivityJPanel);
    }//GEN-LAST:event_btnViewOrderHistoryActionPerformed

    private void btnPlaceShippingOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceShippingOrderActionPerformed
        // TODO add your handling code here:

        InventoryPlaceShippingOrderJPanel managerOrderJPanel = new InventoryPlaceShippingOrderJPanel(account, countyEnterpriseArray, vendor);
        ActivityJPanel.add("InventoryPlaceShippingOrderJPanel", managerOrderJPanel);
        CardLayout layout = (CardLayout)ActivityJPanel.getLayout();
        layout.next(ActivityJPanel);

    }//GEN-LAST:event_btnPlaceShippingOrderActionPerformed

    private void btnAssignDeliveryPartnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignDeliveryPartnerActionPerformed
        // TODO add your handling code here:

        InventoryManagerAssignDeliveryJPanel manageShippingPartnerJPanel = new InventoryManagerAssignDeliveryJPanel(account, countyEnterpriseArray, vendor);
        ActivityJPanel.add("InventoryManagerAssignDeliveryJPanel", manageShippingPartnerJPanel);
        CardLayout layout = (CardLayout)ActivityJPanel.getLayout();
        layout.next(ActivityJPanel);
    }//GEN-LAST:event_btnAssignDeliveryPartnerActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        DB4OUtil.getInstance().storeSystem(system);
        MainJFrame.mainPanel.remove(this);
        CardLayout layout = (CardLayout) MainJFrame.mainPanel.getLayout();
        layout.first(MainJFrame.mainPanel);
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ActivityJPanel;
    private javax.swing.JPanel OptionsJPanel;
    private javax.swing.JButton btnAssignDeliveryPartner;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPlaceShippingOrder;
    private javax.swing.JButton btnViewOrderHistory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
